#!/bin/sh
#PBS -N testongreenium3
#PBS -l select=1:ncpus=12:mem=48gb,walltime=2:00:00
#PBS -M yuhao.liu@unsw.edu.au
#PBS -m ae
date
cd V4
module load matlab/R2022a
matlab -nodisplay -nosplash -r testongreenium3
date